# Перенаправление всех HTTP-запросов на HTTPS
server {
    listen 80;
    server_name smmdeck.ru www.smmdeck.ru;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name smmdeck.ru www.smmdeck.ru;
    client_max_body_size 50M;

    
    ssl_certificate /etc/letsencrypt/live/smmdeck.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smmdeck.ru/privkey.pem;

    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https; 
    }

    location /uploads/ {
        proxy_pass http://backend:5000/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}