version: '3.8'

services:
  # 1. Наша база данных (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: smmbox_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: smmbox
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 2. Наш Бэкенд
  backend:
    build: ./backend
    container_name: smmbox_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:superpassword123@db:5432/smmbox?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - VK_APP_ID=${VK_APP_ID}
      - VK_APP_SECRET=${VK_APP_SECRET}
      - VK_SERVICE_TOKEN=${VK_SERVICE_TOKEN}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=5000
    depends_on:
      - db

  # 3. Наш Фронтенд (React + Nginx)
  frontend:
    build: ./frontend
    container_name: smmbox_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

# Место, где физически будут храниться данные базы
volumes:
  pgdata: